### ISSUE TITLE
Users are not activated by default

### ISSUE THREAD

**Issue by lucosius** [verbb/social-login#24] opened 2024-04-06 11:47 UTC
### Describe the bug

Hello,

I have an issue where all the new users are set as inactive. Verification is off on CraftCMS, Force Activation is on.

### Steps to reproduce

I tried to create config file but that didn't help. Not sure how to solve this issue.

### Craft CMS version

Craft Pro 4.8.7

### Plugin version

1.0.13

### Multi-site?

No

### Additional context

Other plugins:

AsyncQueue	3.1.1
Bulk Edit	4.0.1
Comments	2.0.11
Control Panel Nav	4.0.12
Feed Me	5.4.0
oEmbed	3.0.8
Poll	2.1.0
Redactor	3.0.4
Retour	4.1.16
SEOmatic	4.0.45
Social Login	1.0.13
Sprig	2.8.0
TimeAgo	1.1.0
Upvote	2.3.3
Views Work	2.2.0
Wordsmith	4.4.0

**Comment by engram-design** [comment] 2024-04-06 12:25
Have you enabled the [forceActivate](https://verbb.io/craft-plugins/social-login/docs/get-started/configuration) config setting?

Otherwise, this should follow the default behaviour of Craft when registering new users.

**Comment by lucosius** [comment] 2024-04-06 12:39
Yes, it's activated.

I figured out that it's somehow related with the "Populate User Profile" setting. I have fields mapped like this
![Screenshot (6)](https://github.com/verbb/social-login/assets/80326468/993f3d50-2cc7-45b6-af13-ce1852b38258)

If I disable this option - the user is activated after registration but if it's enabled - not.

**Comment by engram-design** [comment] 2024-04-06 12:45
That seems odd, the mappings look pretty okay to me. Even if you reduce it to its most basic of just email?

Anything in your `/storage/logs/social-login.log` files?

**Comment by StuartMcD** [comment] 2024-06-06 13:27
Can confirm similar behaviour after recent upgrade.
Craft: 4.9.3 to 4.9.7
Social: 1.0.13 to 1.0.15

Process works as intended but the user record created status is: `Inactive` and no confirmation email is sent.  Am requiring manual confirmation.  If I set, Force activation to true, it works fine.

No error logs. No configuration file.

Am also running Freeform and using their integration to create user account and works fine.

![image](https://github.com/verbb/social-login/assets/5855813/c780436e-5e66-4e6c-9cc1-0e57ef0999bc)

**Comment by engram-design** [comment] 2024-06-07 04:34
Just added a "Send Activation Email" plugin setting to control this, which is default to enabled. To get this early, run `composer require verbb/social-login:"dev-craft-4 as 1.0.15"`.

**Comment by StuartMcD** [comment] 2024-06-07 06:43
Thx for the super quick work done here.

I've ran the required, visited the backend, all things look normal, on registration, the user is created and set to 'active' but no email is sent. All options are set accordingly, so to Crafts user settings.

Bonus Friday bug?? The redirect has stopped working too. The return URL is populated and can be inspected but upon return from the service, it returns to the same page.

**Comment by engram-design** [comment] 2024-06-09 23:16
My mistake, that should be fixed now. Run `composer require verbb/social-login:"dev-craft-4 as 1.0.15"`.

**Comment by StuartMcD** [comment] 2024-06-11 01:14
Ahhh yes, that fix works for the sending of confirmation email.

Unfortunately, it's no longer honouring the redirect; should I start a new ticket?

**Comment by engram-design** [comment] 2024-06-11 02:46
Hmmm, yep maybe start a new ticket. There have been some redirect improvements, but should mostly revolve around headless setups.

**Comment by engram-design** [comment] 2024-08-11 00:17
Fixed in [1.0.16](https://github.com/verbb/social-login/releases/tag/1.0.16)

**Closed as completed by engram-design** 2024-08-11 00:17 UTC
